name: OctoBot Tulipy - Build and push
on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  pull_request:

jobs:
  tests:
    name: ${{ matrix.os }}${{ matrix.arch }} - ${{ matrix.type }} - tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        arch: [ x64 ]
        type: [ cython ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.X'
        architecture: ${{ matrix.arch }}

    - name: Install dependencies
      run: pip install --prefer-binary -r dev_requirements.txt -r requirements.txt

    - name: Compile project
      run: |
        python setup.py build_ext --inplace
        python setup.py install

    - name: Tests
      run: python tests/test.py

  publish:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: [tests]
    uses: Drakkar-Software/.github/.github/workflows/python3_wheel_workflow.yml@master
    secrets:
      PYPI_OFFICIAL_UPLOAD_URL: ${{ secrets.PYPI_OFFICIAL_UPLOAD_URL }}
      PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

  notify:
    if: ${{ failure() }}
    needs:
      - tests
      - publish
    uses: Drakkar-Software/.github/.github/workflows/failure_notify_workflow.yml@master
    secrets:
      DISCORD_GITHUB_WEBHOOK: ${{ secrets.DISCORD_GITHUB_WEBHOOK }}
