name: OctoBot Tulipy - Build and push
on:
  push:
    branches:
      - 'master'
      - 'add-mobile-wheels'
    tags:
      - '*'
  pull_request:

jobs:
  tests:
    name: ${{ matrix.os }}${{ matrix.arch }} - ${{ matrix.type }} - tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        arch: [ x64 ]
        type: [ cython ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13.X'
        architecture: ${{ matrix.arch }}

    - name: Install dependencies
      run: pip install --prefer-binary -r dev_requirements.txt -r requirements.txt

    - name: Compile project
      run: |
        python setup.py build_ext --inplace
        python setup.py install

    - name: Tests
      run: python tests/test.py

  publish:
    uses: Drakkar-Software/.github/.github/workflows/python3_wheel_workflow.yml@add-mobile-wheels
    with:
      build_mobile_wheels: true
      python_version: 3.13.X
    secrets:
      PYPI_OFFICIAL_UPLOAD_URL: ${{ secrets.PYPI_OFFICIAL_UPLOAD_URL }}
      PYPI_USERNAME: __token__
      PYPI_PASSWORD: ${{ secrets.PYPI_TOKEN }}

  notify:
    if: ${{ failure() }}
    needs:
      - tests
      - publish
    uses: Drakkar-Software/.github/.github/workflows/failure_notify_workflow.yml@master
    secrets:
      DISCORD_GITHUB_WEBHOOK: ${{ secrets.DISCORD_GITHUB_WEBHOOK }}
